const products = [
  // Mrówki
  {
    id: 0,
    name: "Messor barbarus",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
    category: "Mrówki",
    price: 69.95,
    image: "./images/messor-barbarus.png",
    sale: true,
    saleAmount: 10,
  },
  {
    id: 1,
    name: "Camponotus Ligniperda",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
    category: "Mrówki",
    price: 50.99,
    image: "./images/camponotus-ligniperda.png",
    sale: false,
    saleAmount: 0,
  },
  {
    id: 2,
    name: "Acromyrmex Octospinosus",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
    category: "Mrówki",
    price: 899.95,
    image: "./images/acromyrmex-octospinosus.png",
    sale: false,
    saleAmount: 0,
  },

  // Pająki
  {
    id: 3,
    name: "Poecilotheria Metallica",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
    category: "Pająki",
    price: 99.99,
    image: "./images/poecilotheria-metallica.png",
    sale: true,
    saleAmount: 20,
  },
  {
    id: 4,
    name: "Brachypelma Boehmei",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
    category: "Pająki",
    price: 35.00,
    image: "./images/brachypelma-boehmei.png",
    sale: false,
    saleAmount: 0,
  },

  // Węże
  {
    id: 5,
    name: "Wąż Zbożowy",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
    category: "Węże",
    price: 249.99,
    image: "./images/waz-zbozowy.png",
    sale: true,
    saleAmount: 40,
  },
  {
    id: 6,
    name: "Pyton Tygrysi",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
    category: "Węże",
    price: 99.99,
    image: "./images/pyton-trygrysi.png",
    sale: false,
    saleAmount: 0,
  },

  //Modliszki
  {
    id: 7,
    name: "Phyllocrania paradoxa",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
    category: "Modliszki",
    price: 30.99,
    image: "./images/phyllocrania-paradoxa.png",
    sale: false,
    saleAmount: 0,
  },
  {
    id: 8,
    name: "Hymenopus coronatus",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
    category: "Modliszki",
    price: 54.99,
    image: "./images/hymenopus-coronatus.png",
    sale: false,
    saleAmount: 0,
  },
];